language: python
matrix:
    include:
        -   env: TOXENV=py27 GO=1.10
        -   env: TOXENV=py27 GO=1.11
        -   env: TOXENV=py36 GO=1.11
            python: 3.6
        -   env: TOXENV=pypy GO=1.11
            python: pypy
install:
    - |
        export GOPATH=~/gopath
        export PATH="$GOPATH/bin:$PATH"
        export TRAVIS_BUILD_DIR="$GOPATH/src/github.com/$TRAVIS_REPO_SLUG"
        mkdir -p "$TRAVIS_BUILD_DIR"
        rsync -az . "$TRAVIS_BUILD_DIR"
        cd "$TRAVIS_BUILD_DIR"
        eval "$(gimme $GO)"
    - pip install coveralls tox
script:
    - go get -t
    - go test -v
    - tox
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pre-commit
